filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

tools:
    external_code_coverage:
        timeout: 700

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true

    php_cs_fixer:
        enabled: true

    php_hhvm:
        enabled: true

    php_mess_detector:
        enabled: true

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true

    sensiolabs_security_checker: true
