language: php
php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer --prefer-source --dev install

script:
  - phpunit --coverage-clover=coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
